Repository Field-Passer/newFieldPasser-FE, pull requests merged in 2023-07, with the labels that each got.

#19 Design: screen max-width 수정
  src/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Overlay.tsx
  src/components/Sidebar.tsx
  src/constants/theme.ts
  src/globalStyles.ts
  src/hooks/useScreenHook.tsx
Labels: Design

#21 Design: 게시글 작성 페이지 ui 구성
  public/upload.png
  src/App.tsx
  src/components/Footer.tsx
  src/components/Overlay.tsx
  src/components/Sidebar.tsx
  src/constants/options.ts
  src/pages/BoardForm.tsx
Labels: Feature, Design

#22 Feat: 마이 페이지 마크업
  public/calendar.svg
  public/chat_bubble.svg
  public/fill_heart.svg
  public/test_image.png
  src/components/MobileMenu.tsx
  src/components/MyPage/BoardCard.tsx
  src/components/MyPage/CardLists.tsx
  src/components/MyPage/CommentLists.tsx
  src/components/Title.tsx
  src/constants/pathConst.ts
  src/globalStyles.ts
  src/pages/Help.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/MyPageDetail.tsx
  src/routes/router.tsx
Labels: Feature, Design

#25 Design: 메인페이지 상단
  public/badminton.svg
  public/basketball.svg
  public/futsal.svg
  public/search_option.svg
  public/soccer.svg
  public/tennis.svg
  src/constants/icons.tsx
  src/pages/BoardForm.tsx
  src/pages/Main.tsx
Labels: Design

#28 Feat: 이미지 업로드 미리보기
  public/futsal.svg
  src/components/Header.tsx
  src/constants/icons.tsx
  src/constants/options.ts
  src/pages/BoardForm.tsx
  src/pages/Main.tsx
Labels: Feature, Design

#29 Feat: 로그인, 로그아웃 api 연결 및 axios 세팅
  package-lock.json
  package.json
  src/api/Instance.tsx
  src/api/authApi.tsx
  src/components/Header.tsx
  src/main.tsx
  src/pages/Login.tsx
  src/storage/Cookie.tsx
  src/store/config.tsx
  src/store/slices/authSlice.tsx
  src/vite-env.d.ts
Labels: API, Feature, Setting

#35 Feat: 로그인 상태별 버튼동작 추가
  src/components/Header.tsx
  src/components/Sidebar.tsx
  src/pages/BoardForm.tsx
  src/pages/Main.tsx
Labels: Feature, Design

#37 Feat: 첨부파일 삭제기능 추가
  public/calendar-dark.png
  public/calendar-light.png
  public/clock-fff.png
  public/clock.png
  public/select-arrow.png
  src/api/Instance.tsx
  src/components/Footer.tsx
  src/components/Sidebar.tsx
  src/constants/helpList.ts
  src/globalStyles.ts
  src/pages/BoardForm.tsx
  src/vite-env.d.ts
Labels: Feature, Design

#38 Feat: 리프레시 토큰 적용
  index.html
  src/api/Instance.tsx
  src/api/authApi.tsx
  src/components/Header.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/storage/Cookie.tsx
  src/store/slices/authSlice.tsx
Labels: API, Feature

#39 Feat: 마이페이지 마크업
  public/my_page_banner/mobile_0.jpg
  public/my_page_banner/mobile_1.jpg
  public/my_page_banner/mobile_2.jpg
  public/my_page_banner/mobile_3.jpg
  public/my_page_banner/pc_0.jpg
  public/my_page_banner/pc_1.jpg
  public/my_page_banner/pc_2.jpg
  public/my_page_banner/pc_3.jpg
  src/components/Board.tsx
  src/components/Inner.tsx
  src/components/MyPage/BoardCard.tsx
  src/components/MyPage/CommentLists.tsx
  src/components/MyPage/PCBoardCard.tsx
  src/components/MyPage/PCCardLists.tsx
  src/components/Title.tsx
  src/constants/icons.tsx
  src/pages/Help.tsx
  src/pages/MyPage.tsx
  src/pages/MyPageDetail.tsx
Labels: Feature, Design

#43 Feat: 게시글 작성 api 연결
  public/basketball0.png
  public/basketball1.png
  public/basketball2.png
  public/futsal0.png
  public/futsal1.png
  public/futsal2.png
  public/soccer0.png
  public/soccer1.png
  public/soccer2.png
  public/tennis0.png
  public/tennis1.png
  public/tennis2.png
  src/api/postApi.tsx
  src/components/Header.tsx
  src/components/Overlay.tsx
  src/components/Sidebar.tsx
  src/constants/options.ts
  src/constants/pathConst.ts
  src/globalStyles.ts
  src/hooks/useScreenHook.tsx
  src/pages/BoardForm.tsx
  src/pages/Write.tsx
  src/routes/router.tsx
Labels: API, Feature, Design

#44 Feat: 회원가입 api 연결 및 input 유효성 검사 적용
  .eslintrc.cjs
  src/api/Instance.tsx
  src/api/authApi.tsx
  src/globalStyles.ts
  src/hooks/useInputHook.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/vite-env.d.ts
Labels: API, Feature, Design

#45 Feat: 게시글 작성 페이지 pc버전 api 연결
  public/badminton0.png
  public/badminton1.png
  public/badminton2.png
  src/pages/Write.tsx
Labels: API, Feature, Design

#47 Feat: 게시글 작성 시 통화단위 콤마 적용
  src/pages/Write.tsx
Labels: Feature

#49 Feat: 비밀번호찾기 페이지 마크업
  src/api/Instance.tsx
  src/api/authApi.tsx
  src/constants/pathConst.ts
  src/pages/FindPassword.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/routes/router.tsx
  src/vite-env.d.ts
Labels: Design

#54 Feat: 비밀번호 찾기 페이지 api 연결
  src/api/Instance.tsx
  src/api/authApi.tsx
  src/components/ResetPassword/ResetPw.tsx
  src/components/ResetPassword/TemporaryPw.tsx
  src/components/ResetPassword/Verification.tsx
  src/pages/FindPassword.tsx
  src/vite-env.d.ts
Labels: API, Feature, Design
