Repository Field-Passer/newFieldPasser-FE, pull requests merged in 2023-08, with the labels that each got.

#58 Feat: 메인페이지 게시글 리스트 지역 필터링 기능 추가
  src/components/TimeSelector.tsx
  src/constants/options.ts
  src/pages/Main.tsx
  src/pages/Write.tsx
Labels: API, Feature, Design

#61 Feat: 게시글 수정 페이지 진입 시 아이디 일치 확인
  src/api/getApi.tsx
  src/api/postApi.tsx
  src/components/TimeSelector.tsx
  src/constants/pathConst.ts
  src/pages/BoardDetails.tsx
  src/pages/Edit.tsx
  src/pages/Main.tsx
  src/pages/Write.tsx
  src/routes/router.tsx
Labels: API, Feature

#65 Feat: 마이페이지 slice 생성
  src/api/authApi.tsx
  src/components/Header.tsx
  src/components/MyPage/CommentLists.tsx
  src/components/MyPage/PCBoardCard.tsx
  src/pages/MyPage.tsx
  src/pages/MyPageDetail.tsx
  src/store/config.tsx
  src/store/slices/infoSlice.tsx
  src/store/slices/wishlistSlice.tsx
  src/vite-env.d.ts
Labels: API

#66 Feat: input data 상태 저장기능 추가
  src/components/Sidebar.tsx
  src/hooks/utils.tsx
  src/pages/Write.tsx
Labels: API, Feature, Design

#67 Feat: 마이 페이지 상세 api 연결 및 수정
  src/components/Board.tsx
  src/components/MobileMenu.tsx
  src/components/MyPage/CommentLists.tsx
  src/components/MyPage/PCBoardCard.tsx
  src/components/MyPage/PCCardLists.tsx
  src/pages/MyPageDetail.tsx
  src/store/config.tsx
  src/store/slices/wishlistSlice.tsx
Labels: API

#69 Feat: 문의글 관련 마크업
  src/api/getApi.tsx
  src/api/postApi.tsx
  src/components/Ask.tsx
  src/components/Header.tsx
  src/components/Title.tsx
  src/constants/pathConst.ts
  src/pages/Help.tsx
  src/pages/HelpForm.tsx
  src/pages/OneOnOne.tsx
  src/routes/router.tsx
  src/vite-env.d.ts
Labels: API, Feature, Design

#71 Feat: 시작시간 오후, 끝나는 시간 오전일 경우 날짜+1
  src/components/Sidebar.tsx
  src/pages/Write.tsx
Labels: API, Feature, Design

#72 Feat: 관심 게시글, 댓글, 게시글 삭제 api 연동
  src/api/authApi.tsx
  src/api/boardApi.tsx
  src/api/getApi.tsx
  src/components/Board.tsx
  src/components/Comment.tsx
  src/components/CommentInput.tsx
  src/components/Header.tsx
  src/constants/icons.tsx
  src/pages/BoardDetails.tsx
  src/pages/BoardList.tsx
  src/pages/Main.tsx
  src/vite-env.d.ts
Labels: API

#75 Feat: 문의글 작성 및 부자연스러운 디자인 변경
  src/api/getApi.tsx
  src/api/postApi.tsx
  src/components/Ask.tsx
  src/components/Header.tsx
  src/components/Inner.tsx
  src/pages/Help.tsx
  src/pages/HelpForm.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/OneOnOne.tsx
  src/vite-env.d.ts
Labels: API, Feature, Design

#76 Feat: 메인페이지 정렬 기능 추가
  src/components/SearchForm.tsx
  src/pages/Main.tsx
  src/pages/Write.tsx
Labels: Feature, BugFix

#79 Feat: 문의 답변 컴포넌트 기능 구현
  src/components/Header.tsx
  src/components/HelpNAskForm.tsx
  src/components/OneOnOne.tsx
  src/constants/pathConst.ts
  src/pages/Ask.tsx
  src/pages/AskAnswerForm.tsx
  src/pages/AskDetail.tsx
  src/pages/HelpForm.tsx
  src/routes/router.tsx
Labels: API, Feature, Refactor

#81 Feat: 메인페이지 게시글 무한스크롤 기능 추가
  src/App.tsx
  src/components/Modal.tsx
  src/components/Overlay.tsx
  src/components/SearchForm.tsx
  src/components/Sidebar.tsx
  src/pages/Main.tsx
  src/vite-env.d.ts
Labels: Feature, Design

#82 Feat: PrivateRoute 적용
  src/api/Instance.tsx
  src/api/authApi.tsx
  src/components/CheckAuthorization.tsx
  src/components/Header.tsx
  src/components/MyPage/UserEdit.tsx
  src/constants/pathConst.ts
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/routes/PrivateRoute.tsx
  src/routes/router.tsx
  src/store/slices/authSlice.tsx
Labels: Feature

#83 Feat: 마이 페이지, 경로 수정
  src/api/authApi.tsx
  src/components/MyPage/CardLists.tsx
  src/components/MyPage/PCBoardCard.tsx
  src/components/SearchForm.tsx
  src/constants/pathConst.ts
  src/pages/MyPage.tsx
  src/pages/MyPageDetail.tsx
Labels: API, Feature, Refactor

#86 Design: 모달 디자인 완성 및 overlay 추가
  src/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Modal.tsx
  src/constants/icons.tsx
  src/vite-env.d.ts
Labels: Feature, Design

#87 Feat: 마이 페이지 관련 오류 수정
  src/pages/Ask.tsx
  src/pages/MyPageDetail.tsx
  src/store/config.tsx
  src/store/slices/wishlistSlice.tsx
Labels: Refactor

#88 Feat: 메인/로그인화면 무한새로고침 오류 수정 외
  src/api/Instance.tsx
  src/api/authApi.tsx
  src/components/CheckAuthorization.tsx
  src/components/Header.tsx
  src/components/Sidebar.tsx
  src/pages/Edit.tsx
  src/pages/MyPageDetail.tsx
  src/pages/UserEdit.tsx
  src/routes/PrivateRoute.tsx
  src/routes/router.tsx
  src/store/slices/authSlice.tsx
Labels: BugFix

#89 Chore: 빌드 테스트를 위한 임시 에러처리
  public/_redirects
  src/components/TimeSelector.tsx
  src/pages/MyPageDetail.tsx
  src/pages/UserEdit.tsx
  src/pages/Write.tsx
  src/store/slices/infoSlice.tsx
  src/store/slices/postDataSlice.tsx
Labels: BugFix

#91 Feat: 마이페이지, 회원 프로필 페이지
  src/api/authApi.tsx
  src/components/Board.tsx
  src/components/MBoardList.tsx
  src/components/MyPage/BoardCard.tsx
  src/components/MyPage/CommentLists.tsx
  src/constants/pathConst.ts
  src/pages/BoradBlind.tsx
  src/pages/MyPage.tsx
  src/pages/MyPageDetail.tsx
  src/pages/Profile.tsx
  src/routes/router.tsx
  src/vite-env.d.ts
Labels: API, Feature, Refactor

#92 Feat: 양도 완료 api 연동, 기타 수정사항
  src/api/boardApi.tsx
  src/components/Board.tsx
  src/components/Comment.tsx
  src/components/SearchForm.tsx
  src/pages/BoardDetails.tsx
  src/pages/BoardList.tsx
  src/pages/Main.tsx
  src/store/slices/searchVlaueSlice.tsx
  src/vite-env.d.ts
Labels: API, BugFix, Design

#93 Feat: 소셜 로그인 추가 중 그 외 자잘한 수정사항
  src/components/SocialLogin.tsx
  src/components/SocialLoginRedirect.tsx
  src/constants/pathConst.ts
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/routes/router.tsx
Labels: API, Feature, Design

#95 Feat: 타임셀렉터 기능 완성
  .eslintrc.cjs
  .prettierrc.json
  src/App.tsx
  src/api/boardApi.tsx
  src/components/Board.tsx
  src/components/Comment.tsx
  src/components/Footer.tsx
  src/components/HelpNAskForm.tsx
  src/components/Modal.tsx
  src/components/MyPage/CommentLists.tsx
  src/components/MyPage/PCBoardCard.tsx
  src/components/ResetPassword/ResetPw.tsx
  src/components/ResetPassword/Verification.tsx
  src/components/SearchForm.tsx
  src/components/TimeSelector.tsx
  src/constants/helpList.ts
  src/constants/icons.tsx
  src/pages/Ask.tsx
  src/pages/AskDetail.tsx
  src/pages/BoardDetails.tsx
  src/pages/BoardList.tsx
  src/pages/Join.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/MyPageDetail.tsx
  src/pages/Profile.tsx
  src/pages/UserEdit.tsx
  src/pages/Write.tsx
  src/store/slices/searchVlaueSlice.tsx
  src/vite-env.d.ts
Labels: Feature, Design
