Repository Field-Passer/newFieldPasser-FE, pull requests merged in 2023-10, with the labels that each got.

#113 Docs: README.md 작성
  Readme.md
  public/vite.svg
  src/pages/Error.tsx
  src/pages/Main.tsx
Labels: BugFix, Docs

#114 Refactor: 무한스크롤 코드 커스텀훅 분리, 로딩 컴포넌트 추가
  package-lock.json
  package.json
  src/api/boardApi.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Modal.tsx
  src/components/loading.tsx
  src/constants/icons.tsx
  src/constants/options.ts
  src/hooks/useInfinityScroll.tsx
  src/hooks/useModal.tsx
  src/pages/Main.tsx
  src/vite-env.d.ts
Labels: Refactor

#119 Refactor: 게시글 작성, 수정 페이지 컴포넌트 분리 및 state 정리
  src/components/Header.tsx
  src/components/Sidebar.tsx
  src/components/Write/CategorySelect.tsx
  src/components/Write/ContentInput.tsx
  src/components/Write/DateInput.tsx
  src/components/Write/DistrictSelect.tsx
  src/components/Write/FileUpload.tsx
  src/components/Write/PriceInput.tsx
  src/components/Write/TitleInput.tsx
  src/components/Write/Write.tsx
  src/components/common/TimeSelector.tsx
  src/components/common/loading.tsx
  src/hooks/useTimeSelector.tsx
  src/pages/EditPost.tsx
  src/pages/Main.tsx
  src/pages/Write.tsx
  src/pages/WritePost.tsx
  src/routes/router.tsx
  src/vite-env.d.ts
Labels: Refactor

#123 Refactor: 리팩토링
  src/App.tsx
  src/api/Instance.tsx
  src/api/authApi.tsx
  src/api/boardApi.tsx
  src/api/getApi.tsx
  src/api/postApi.tsx
  src/api/userApi.tsx
  src/components/Authrization/CheckAuthorization.tsx
  src/components/Main/Header.tsx
  src/components/MyPage/CommentLists.tsx
  src/components/ResetPassword/ResetPw.tsx
  src/components/ResetPassword/TemporaryPw.tsx
  src/components/ResetPassword/Verification.tsx
  src/components/SocialLogin/SocialLogin.tsx
  src/components/SocialLogin/SocialLoginRedirect.tsx
  src/hooks/useAxiosInterceptor.tsx
  src/hooks/useInfinityScroll.tsx
  src/hooks/useLoginState.tsx
  src/pages/EditPost.tsx
  src/pages/FindPassword.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/MyPageDetail.tsx
  src/pages/Profile.tsx
  src/pages/UserEdit.tsx
  src/routes/PrivateRoute.tsx
  src/routes/router.tsx
  src/store/config.tsx
  src/store/slices/authSlice.tsx
Labels: BugFix, Refactor

#124 Feat: 무한스크롤 후 다시 정렬하기 버튼 추가
  src/components/Main/Footer.tsx
  src/components/Main/ReorderButton.tsx
  src/components/SearchForm.tsx
  src/components/Write/Write.tsx
  src/hooks/useTimeSelector.tsx
  src/pages/BoardDetails.tsx
  src/pages/Main.tsx
  src/vite-env.d.ts
Labels: Refactor

#127 Refactor: Modal 수정
  src/api/postApi.tsx
  src/pages/AskDetail.tsx
  src/pages/BoardDetails.tsx
  src/pages/MyPageDetail.tsx
Labels: BugFix, Refactor

#128 Refactor: 이전 모달 컴포넌트 삭제 및 현재 모달 폴더 이동
  src/App.tsx
  src/components/Main/Footer.tsx
  src/components/ModalWithHook.tsx
  src/components/common/Modal.tsx
Labels: Refactor

#129 Feat: 구글, 네이버 사이트 등록 메타태그 추가
  index.html
  public/logo.png
  public/robots.txt
  public/sitemap.xml
  src/components/Main/Footer.tsx
  src/components/Main/Header.tsx
  src/components/Main/Sidebar.tsx
  src/hooks/useInfinityScroll.tsx
Labels: Feature, Refactor

#130 Fix: robots.txt에 sitemap속성 추가
  public/robots.txt
  src/components/Main/Header.tsx
  src/pages/BoradBlind.tsx
Labels: BugFix

#131 Refactor, Docs: 이미지 형식 webp로 변환, README.md 템플릿 수정
  Readme.md
  public/badminton0.png
  public/badminton0.webp
  public/badminton1.png
  public/badminton1.webp
  public/badminton2.png
  public/badminton2.webp
  public/banner0.png
  public/banner0.webp
  public/banner1.png
  public/banner1.webp
  public/banner2.png
  public/banner2.webp
  public/banner3.png
  public/banner3.webp
  public/banner4.png
  public/banner4.webp
  public/basketball0.png
  public/basketball0.webp
  public/basketball1.png
  public/basketball1.webp
  public/basketball2.png
  public/basketball2.webp
  public/futsal0.png
  public/futsal0.webp
  public/futsal1.png
  public/futsal1.webp
  public/futsal2.png
  public/futsal2.webp
  public/logo.png
  public/logo.webp
  public/og_banner.png
  public/soccer0.png
  public/soccer0.webp
  public/soccer1.png
  public/soccer1.webp
  public/soccer2.png
  public/soccer2.webp
  public/tennis0.png
  public/tennis0.webp
  public/tennis1.png
  public/tennis1.webp
  public/tennis2.png
  public/tennis2.webp
  src/components/Main/Footer.tsx
  src/components/Main/Header.tsx
  src/components/Main/Sidebar.tsx
  src/globalStyles.ts
  src/pages/Error.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/utils/utils.tsx
Labels: Docs, Refactor

#134 Docs: README.md 수정
  Readme.md
Labels: Docs
