Repository Field-Passer/newFieldPasser-FE, pull requests merged in 2023-06, with the labels that each got.

#3 Style: 스타일변수 추가 및 글로벌스타일 적용
  Readme.md
  src/globalStyles.ts
  src/main.tsx
Labels: Setting

#4 Feat: 반응형 웹 패키지 설치 및 hook 구현
  package-lock.json
  package.json
  src/api/Instance.tsx
  src/components/Inner.tsx
  src/hooks/useScreenHook.tsx
  src/pages/Help.tsx
  src/pages/Main.tsx
Labels: Feature, Design, Setting

#7 Env: 스타일변수 객체로 분리
  index.html
  public/favicon.ico
  public/logo.png
  src/components/Header.tsx
  src/globalStyles.ts
Labels: Design, Setting

#9 Feat: 고객센터 자주 묻는 질문 퍼블리싱
  src/components/Ask.tsx
  src/constants/helpList.ts
  src/globalStyles.ts
  src/pages/Help.tsx
Labels: Design

#13 Design: 모바일 헤더 추가, 사이드바 구성
  package-lock.json
  package.json
  public/close.svg
  public/my_comment.svg
  public/my_heart.svg
  public/my_page.svg
  public/my_post.svg
  src/components/Header.tsx
  src/components/Sidebar.tsx
  src/globalStyles.ts
Labels: Design

#14 Design: 푸터 추가
  src/components/Footer.tsx
Labels: Design

#17 Feat: 사이드바 임시 상태관리
  src/App.tsx
  src/components/Header.tsx
  src/components/Sidebar.tsx
Labels: Feature, Design
